

--END VERSION 

--пишем выше
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT SELECT ON TABLES TO "lk";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT INSERT ON TABLES TO "lk";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT UPDATE ON TABLES TO "lk";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT DELETE ON TABLES TO "lk";
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo GRANT EXECUTE ON FUNCTIONS TO "lk";
GRANT ALL ON SCHEMA dbo TO postgres;
GRANT ALL ON SCHEMA dbo TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo
    GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES
    TO lk;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo
    GRANT EXECUTE ON FUNCTIONS
    TO lk;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA dbo TO lk;
GRANT UPDATE ON ALL SEQUENCES IN SCHEMA dbo TO lk;
insert into dbo.version (version,date) values ('dbbuild 1', now());